export const SCREENS = {
  LANDING: 'landing',
  Animation1: 'Card Flip Animation',
  Animation2: 'Drag and Drop',
  Animation3: 'On Scroll',
  Animation4: '3D Geometry',
  Animation5: 'Instagram Like',
  Animation6: 'Color Picker',
  Animation7: 'Progress Bar',
  Animation8: 'Swip to delete',
  Animation9: 'Sliding Counter',
  Animation10: 'Clock Loader',
  Animation11: 'Scroll List',
  Animation12: 'Header Toggle',
};
